import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowLeft,
  ShieldCheck,
  Warning,
  CheckCircle,
  SealCheck,
} from "@phosphor-icons/react/dist/ssr";
import { Section, SectionHeader } from "@/components/section";
import { Reveal } from "@/components/reveal";
import { Button } from "@/components/button";
import { CodeBlock } from "@/components/code-block";
import bundle from "@/lib/demo-bundle.json";

export const metadata: Metadata = {
  title: "Red-to-green demo — StepStitch",
  description:
    "Watch one user-reported bug travel the full StepStitch loop: structural capture, privacy scrub, replayability score, Playwright repro, ticket/PR drafts, verdict derivation, and a confirmed-fixed regression entry. Every artifact is generated by the real service from a synthetic scenario — drafts are dry-run, nothing is sent.",
};

// The bundle is generated by `npm run demo` (scripts/demo_red_to_green.py) and kept in sync
// by the drift guard in service/tests/test_demo_bundle.py — the generator is the source of
// truth for the shape; these types cover just the fields this page renders.
type TimelineRow = {
  index: number;
  kind: string;
  label: string;
  selector?: string;
  detail?: string;
};
type ReplayWarning = { code: string; detail?: string; step_index?: number };
type DemoBundle = {
  delivery: string;
  story: string[];
  steps: {
    "1_bug_report": {
      headline: string;
      raw_unsafe_input: { note: string; forbidden_fields_sent: string[]; explanation: string };
    };
    "2_structural_capture": { timeline: TimelineRow[] };
    "3_privacy_scrub": {
      scrub_status: string;
      scrubbed_fields: string[];
      explanation_after_scrub: string;
      never_captured: string[];
    };
    "4_replayability": {
      score: number;
      grade: string;
      warnings: ReplayWarning[];
      signals: Record<string, number>;
    };
    "5_playwright_repro": { playwright_code: string };
    "6_drafts": {
      delivery: string;
      servicenow: Record<string, unknown>;
      salesforce: Record<string, unknown>;
      genesys: Record<string, unknown>;
      github: { pull_request: { would_open: { branch: string }; note: string } };
    };
    "7_ci_verification": { verdict: string; note: string };
    "8_regression_corpus": { entries: unknown[] };
  };
};

const data = bundle as unknown as DemoBundle;
const steps = data.steps;
const story = data.story;

export default function DemoPage() {
  const scrub = steps["3_privacy_scrub"];
  const replay = steps["4_replayability"];
  const drafts = steps["6_drafts"];
  const verify = steps["7_ci_verification"];
  const corpus = steps["8_regression_corpus"];
  const raw = steps["1_bug_report"].raw_unsafe_input;

  return (
    <main id="main" className="flex-1">
      <Section className="pt-12">
        <Reveal>
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-muted transition-colors hover:text-fg"
          >
            <ArrowLeft size={14} weight="bold" /> Back home
          </Link>
        </Reveal>
        <div className="mt-6">
          <SectionHeader
            eyebrow="Red-to-green demo"
            title="One bug, the whole loop, no credentials"
            body="Every panel below is generated by the real StepStitch service modules — the same scrubber, scorer, compiler, draft adapters, and verdict logic the live product runs. There is no database and no ServiceNow/Salesforce/GitHub/cloud credential anywhere. Drafts and the pull request are dry-run previews; nothing is ever sent."
          />
        </div>

        {/* Dry-run banner */}
        <Reveal>
          <div className="mt-8 inline-flex items-center gap-2 rounded-full border border-ok/30 bg-ok/10 px-3 py-1.5 text-[13px] font-medium text-ok">
            <ShieldCheck size={15} weight="bold" />
            Demo data · {bundle.delivery}
          </div>
        </Reveal>

        {/* Flow strip */}
        <Reveal>
          <ol className="mt-6 flex flex-wrap items-center gap-x-2 gap-y-2 text-[12.5px] text-muted">
            {story.map((s, i) => (
              <li key={s} className="flex items-center gap-2">
                <span className="rounded-md border border-line bg-surface-2/50 px-2 py-1">{s}</span>
                {i < story.length - 1 ? <span className="text-accent">→</span> : null}
              </li>
            ))}
          </ol>
        </Reveal>

        <div className="mt-10 grid gap-4">
          {/* 1 + 2 */}
          <Reveal>
            <div className="grid gap-4 md:grid-cols-2">
              <StepCard n={1} title="User reports a bug">
                <p className="text-[14px] text-fg">{steps["1_bug_report"].headline}</p>
                <p className="mt-3 text-xs font-medium uppercase tracking-wide text-muted">
                  Forbidden fields the SDK sent (placeholders only)
                </p>
                <div className="mt-2 flex flex-wrap gap-2">
                  {raw.forbidden_fields_sent.map((f: string) => (
                    <span
                      key={f}
                      className="rounded-md border border-line bg-surface-2/50 px-2 py-1 font-mono text-[11.5px] text-muted line-through decoration-bad/50"
                    >
                      {f}
                    </span>
                  ))}
                </div>
                <p className="mt-3 text-[12px] italic text-muted">{raw.note}</p>
              </StepCard>

              <StepCard n={2} title="Structural footsteps only">
                <ol className="grid gap-px overflow-hidden rounded-xl border border-line">
                  {steps["2_structural_capture"].timeline.map((t) => (
                    <li key={t.index} className="bg-surface px-3 py-2">
                      <p className="text-[13px] font-medium text-fg">{t.label}</p>
                      <p className="truncate font-mono text-[11.5px] text-muted">
                        {t.selector ?? t.detail}
                      </p>
                    </li>
                  ))}
                </ol>
              </StepCard>
            </div>
          </Reveal>

          {/* 3 — privacy scrub */}
          <Reveal>
            <StepCard n={3} title="The server scrubber proves no NPI persisted">
              <div className="flex items-center gap-2 text-sm font-semibold text-ok">
                <ShieldCheck size={17} weight="bold" />
                Scrub status: {scrub.scrub_status}
              </div>
              <div className="mt-4 grid gap-5 md:grid-cols-2">
                <div>
                  <p className="text-xs font-medium uppercase tracking-wide text-muted">
                    Fields dropped or redacted before storage
                  </p>
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {scrub.scrubbed_fields.map((f: string) => (
                      <span key={f} className="rounded-md bg-surface-2 px-2 py-1 font-mono text-[11.5px] text-fg">
                        {f}
                      </span>
                    ))}
                  </div>
                  <p className="mt-3 font-mono text-[12px] text-muted">
                    explanation → {scrub.explanation_after_scrub}
                  </p>
                </div>
                <div>
                  <p className="text-xs font-medium uppercase tracking-wide text-muted">Never captured</p>
                  <ul className="mt-2 grid gap-1.5 text-[13px] text-muted">
                    {scrub.never_captured.map((n: string) => (
                      <li key={n} className="flex items-start gap-2">
                        <span className="mt-1.5 size-1 shrink-0 rounded-full bg-bad/70" aria-hidden />
                        {n}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </StepCard>
          </Reveal>

          {/* 4 + 5 */}
          <Reveal>
            <div className="grid gap-4 md:grid-cols-2">
              <StepCard n={4} title="Replayability score">
                <div className="flex items-baseline gap-3">
                  <span className="text-4xl font-semibold tabular-nums text-fg">{replay.score}</span>
                  <span className="rounded-md bg-accent-solid px-2 py-0.5 text-sm font-semibold text-accent-fg">
                    grade {replay.grade}
                  </span>
                </div>
                <div className="mt-4 grid grid-cols-3 gap-2 text-center">
                  {Object.entries(replay.signals).map(([k, v]) => (
                    <div key={k} className="rounded-lg border border-line bg-surface-2/40 px-2 py-2">
                      <p className="font-mono text-lg font-semibold text-fg">{String(v)}</p>
                      <p className="text-[11px] text-muted">{k.replace(/_/g, " ")}</p>
                    </div>
                  ))}
                </div>
                {replay.warnings?.length ? (
                  <ul className="mt-3 grid gap-1.5">
                    {replay.warnings.map((w, i) => (
                      <li key={i} className="flex items-start gap-2 text-[12.5px] text-muted">
                        <Warning size={14} weight="bold" className="mt-0.5 shrink-0 text-accent" />
                        <span className="font-mono text-fg">{w.code}</span>
                      </li>
                    ))}
                  </ul>
                ) : null}
              </StepCard>

              <StepCard n={5} title="Generated Playwright repro">
                <CodeBlock code={steps["5_playwright_repro"].playwright_code} caption="Red while broken, green once fixed." />
              </StepCard>
            </div>
          </Reveal>

          {/* 6 — drafts */}
          <Reveal>
            <StepCard n={6} title="Ticket & PR drafts — created, never sent">
              <span className="inline-flex rounded-full border border-line bg-surface-2/50 px-2 py-0.5 text-[11px] text-muted">
                {drafts.delivery}
              </span>
              <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                {(["servicenow", "salesforce", "genesys"] as const).map((name) => (
                  <div key={name} className="rounded-xl border border-line bg-surface-2/40 p-4">
                    <p className="text-[13px] font-semibold capitalize text-fg">{name}</p>
                    <p className="mt-1 text-[12px] text-muted">
                      {Object.keys(drafts[name]).length} flat fields · correlation id linked
                    </p>
                  </div>
                ))}
                <div className="rounded-xl border border-line bg-surface-2/40 p-4">
                  <p className="text-[13px] font-semibold text-fg">GitHub</p>
                  <p className="mt-1 text-[12px] text-muted">
                    issue + dry-run PR on{" "}
                    <span className="font-mono">{drafts.github.pull_request.would_open.branch}</span>
                  </p>
                </div>
              </div>
              <p className="mt-3 text-[12px] italic text-muted">
                {drafts.github.pull_request.note}
              </p>
            </StepCard>
          </Reveal>

          {/* 7 + 8 */}
          <Reveal>
            <div className="grid gap-4 md:grid-cols-2">
              <StepCard n={7} title="The verdict logic turns red-to-green into proof">
                <div className="grid gap-2">
                  <Row label="Pre-fix run (bug present)" value="failed" bad />
                  <Row label="Post-fix run (after the fix)" value="passed" />
                  <div className="mt-2 flex items-center gap-2 rounded-lg border border-ok/30 bg-ok/10 px-3 py-2 text-sm font-semibold text-ok">
                    <CheckCircle size={16} weight="bold" />
                    verdict: {verify.verdict}
                  </div>
                  <p className="text-[12px] text-muted">{verify.note}</p>
                  <p className="text-[12px] text-muted">
                    Provenance: in this offline demo the two outcomes above are declared
                    synthetic inputs — no CI ran here. The verdict logic that derives
                    confirmed_fixed from them is the production code, and the shipped CI
                    workflow measures both runs for real. Every release also proves the
                    generated test executes: CI runs a compiled reproduction in Chromium
                    red, then green.
                  </p>
                </div>
              </StepCard>

              <StepCard n={8} title="Recorded in the regression corpus">
                <div className="flex items-center gap-2 text-sm font-semibold text-fg">
                  <SealCheck size={17} weight="bold" className="text-ok" />
                  {corpus.entries.length} confirmed-fixed entry
                </div>
                <p className="mt-3 text-[13.5px] leading-relaxed text-muted">
                  The fix is now durable regression evidence: if this bug ever returns, the committed
                  Playwright test goes red again. That is the moat — a recording cannot do this.
                </p>
              </StepCard>
            </div>
          </Reveal>
        </div>

        <Reveal>
          <div className="mt-10 flex flex-wrap items-center gap-3">
            <Button href="/quickstart" trailingIcon={null}>
              Run it yourself
            </Button>
            <Button href="/financial-services-pilot" variant="secondary" trailingIcon={null}>
              See the pilot
            </Button>
          </div>
        </Reveal>
      </Section>
    </main>
  );
}

function StepCard({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <div className="h-full rounded-2xl border border-line bg-surface p-6">
      <div className="flex items-center gap-3">
        <span className="grid size-7 shrink-0 place-items-center rounded-full bg-accent-solid text-[13px] font-semibold text-accent-fg">
          {n}
        </span>
        <h3 className="text-base font-semibold text-fg">{title}</h3>
      </div>
      <div className="mt-4">{children}</div>
    </div>
  );
}

function Row({ label, value, bad }: { label: string; value: string; bad?: boolean }) {
  return (
    <div className="flex items-center justify-between rounded-lg border border-line bg-surface-2/40 px-3 py-2 text-[13px]">
      <span className="text-muted">{label}</span>
      <span className={`font-mono font-semibold ${bad ? "text-bad" : "text-ok"}`}>{value}</span>
    </div>
  );
}
