"""Deterministic StepStitch -> Playwright compiler.

Pure functions, no I/O, no network, no embedded credentials. Given a trace's
structural footsteps (see contracts/stepstitch.md), emit an executable Playwright
TypeScript reproduction script. Output is fully determined by the inputs so it is
trivially unit-testable.
"""
from __future__ import annotations

from typing import Any, Dict, List

from .replayability import score_trace

__all__ = ["generate_playwright_test"]


def _ts_str(value: str) -> str:
    """Escape a string for a single-quoted TS literal."""
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _comment(text: str) -> str:
    """Sanitize text for a single-line TS comment (no newlines/CR)."""
    return text.replace("\r", " ").replace("\n", " ")


def generate_playwright_test(
    trace_id: str,
    footsteps: List[Dict[str, Any]],
    base_url: str = "http://localhost:3000",
) -> str:
    """Compile footsteps into Playwright TS.

    `base_url` is caller-supplied (no hardcoded host). Routes are templates
    (e.g. ``/accounts/:id``); where a template contains ``:`` a TODO is emitted so the
    engineer substitutes a concrete id. No credentials are ever embedded — auth is left
    as a TODO for the operator to wire to a synthetic/test account.
    """
    base = base_url.rstrip("/")
    replay = score_trace(footsteps)
    lines: List[str] = [
        "import { test, expect } from '@playwright/test';",
        "",
        f"// StepStitch autogenerated reproduction (trace: {_comment(trace_id)})",
        f"// Replayability: {replay['score']:.2f} (grade {replay['grade']})",
    ]
    for w in replay["warnings"]:
        where = f" [step {w['step_index']}]" if "step_index" in w else ""
        lines.append(f"//   ⚠ {w['code']}{where}: {_comment(w['detail'])}")
    lines += [
        "// NOTE: no credentials are embedded. Wire authentication to a synthetic",
        "// test account before running against a protected route.",
        "test('StepStitch reproduction', async ({ page }) => {",
        "  // TODO: authenticate as a synthetic test user if the flow requires it.",
        "",
    ]

    for step in footsteps:
        step_type = str(step.get("type", "")).lower()
        route = str(step.get("route", "/"))
        target = step.get("target")
        label = str(step.get("label", ""))
        metadata = step.get("metadata") or {}

        lines.append(f"  // [{step_type.upper()}] {_comment(route)}")

        if step_type == "navigation":
            if ":" in route:
                lines.append(f"  // TODO: substitute id(s) in templated route '{_comment(route)}'")
            lines.append(f"  await page.goto('{_ts_str(base + route)}');")

        elif step_type == "click" and target:
            if label and label != "[masked]":
                lines.append(f"  // label: {_comment(label)}")
            lines.append(f"  await page.locator('{_ts_str(target)}').click();")

        elif step_type == "input" and target:
            lines.append("  // value redacted by StepStitch; fill a test value:")
            lines.append(
                f"  await page.locator('{_ts_str(target)}').fill('stepstitch-test-value');"
            )

        elif step_type == "api_error":
            status = metadata.get("status", "?")
            endpoint = _comment(str(metadata.get("endpoint", "")))
            lines.append(f"  // expected API failure: {endpoint} (HTTP {status})")

        elif step_type == "exception":
            name = _comment(str(metadata.get("name", "Error")))
            lines.append(f"  // client exception observed here: {name}")

        lines.append("")

    lines.append("  await page.waitForTimeout(1000);")
    return "\n".join(lines) + "\n});\n"
