"""Deterministic StepStitch -> Playwright compiler.

Pure functions, no I/O, no network, no embedded credentials. Given a trace's
structural footsteps (see contracts/stepstitch.md), emit an executable Playwright
TypeScript reproduction script. Output is fully determined by the inputs so it is
trivially unit-testable.

The compiled test is a real regression test: a captured API failure becomes an
armed ``page.waitForResponse`` (matched on URL + method, so it resolves whether or
not the bug is present) plus a status assertion, and a captured client exception
becomes a ``pageerror`` assertion. The test therefore FAILS while the bug is
present and PASSES once it is fixed (red -> green).
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from .replayability import score_trace

__all__ = ["generate_playwright_test"]


def _ts_str(value: str) -> str:
    """Escape a string for a single-quoted TS literal."""
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _comment(text: str) -> str:
    """Sanitize text for a single-line TS comment (no newlines/CR)."""
    return text.replace("\r", " ").replace("\n", " ")


def _coerce_status(value: Any) -> Optional[int]:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _url_prefix(endpoint: str) -> str:
    """Literal URL prefix before the first templated segment.

    ``/api/accounts/:id/transfers`` -> ``/api/accounts/`` so ``url().includes(...)``
    matches the concrete runtime URL (``/api/accounts/123/transfers``).
    """
    if not endpoint:
        return ""
    marker = endpoint.find("/:")
    if marker != -1:
        return endpoint[: marker + 1]
    colon = endpoint.find(":")
    if colon != -1:
        return endpoint[:colon]
    return endpoint


def _status_assertion(var: str, status: Optional[int], endpoint: str) -> str:
    ep = _comment(endpoint or "the endpoint")
    if status is not None and status >= 500:
        return f"  expect({var}.status(), 'no server error from {ep}').toBeLessThan(500);"
    if status is not None:
        return f"  expect({var}.status(), '{ep} must not return {status}').not.toBe({status});"
    return f"  expect({var}.status(), '{ep} must succeed').toBeLessThan(400);"


def _arm_wait(var: str, prefix: str, method: str) -> List[str]:
    method_clause = (
        f" && r.request().method() === '{_ts_str(method.upper())}'" if method else ""
    )
    return [
        f"  const {var} = page.waitForResponse(",
        f"    (r) => r.url().includes('{_ts_str(prefix)}'){method_clause},",
        "  );",
    ]


def generate_playwright_test(
    trace_id: str,
    footsteps: List[Dict[str, Any]],
    base_url: str = "http://localhost:3000",
) -> str:
    """Compile footsteps into Playwright TS.

    `base_url` is caller-supplied (no hardcoded host). Routes are templates
    (e.g. ``/accounts/:id``); where a template contains ``:`` a TODO is emitted so the
    engineer substitutes a concrete id. No credentials are ever embedded — auth is left
    as a TODO for the operator to wire to a synthetic/test account.
    """
    base = base_url.rstrip("/")
    replay = score_trace(footsteps)
    has_exception = any(
        str(s.get("type", "")).lower() == "exception" for s in footsteps
    )

    lines: List[str] = [
        "import { test, expect } from '@playwright/test';",
        "",
        f"// StepStitch autogenerated reproduction (trace: {_comment(trace_id)})",
        f"// Replayability: {replay['score']:.2f} (grade {replay['grade']})",
    ]
    for w in replay["warnings"]:
        where = f" [step {w['step_index']}]" if "step_index" in w else ""
        lines.append(f"//   ⚠ {w['code']}{where}: {_comment(w['detail'])}")
    lines += [
        "// NOTE: no credentials are embedded. Wire authentication to a synthetic",
        "// test account before running against a protected route.",
        "test('StepStitch reproduction', async ({ page }) => {",
        "  // TODO: authenticate as a synthetic test user if the flow requires it.",
        "",
    ]
    if has_exception:
        lines += [
            "  // Capture uncaught client exceptions so we can assert they no longer occur.",
            "  const pageErrors: string[] = [];",
            "  page.on('pageerror', (e) => pageErrors.push(e.message));",
            "",
        ]

    asserted = False
    resp_n = 0

    def emit_action(step_type: str, route: str, target: Optional[str], label: str) -> None:
        if step_type == "navigation":
            if ":" in route:
                lines.append(
                    f"  // TODO: substitute id(s) in templated route '{_comment(route)}'"
                )
            lines.append(f"  await page.goto('{_ts_str(base + route)}');")
        elif step_type == "click" and target:
            if label and label != "[masked]":
                lines.append(f"  // label: {_comment(label)}")
            lines.append(f"  await page.locator('{_ts_str(target)}').click();")
        elif step_type == "input" and target:
            lines.append("  // value redacted by StepStitch; fill a test value:")
            lines.append(
                f"  await page.locator('{_ts_str(target)}').fill('stepstitch-test-value');"
            )

    i = 0
    n = len(footsteps)
    while i < n:
        step = footsteps[i]
        step_type = str(step.get("type", "")).lower()
        route = str(step.get("route", "/"))
        target = step.get("target")
        label = str(step.get("label", ""))
        metadata = step.get("metadata") or {}

        nxt = footsteps[i + 1] if i + 1 < n else None
        nxt_is_api = nxt is not None and str(nxt.get("type", "")).lower() == "api_error"

        lines.append(f"  // [{step_type.upper()}] {_comment(route)}")

        # An interaction immediately followed by an API error: arm the response
        # wait BEFORE the action, then assert on the response after it.
        if step_type in ("navigation", "click", "input") and nxt_is_api and nxt is not None:
            api_meta = nxt.get("metadata") or {}
            endpoint = str(api_meta.get("endpoint", ""))
            status = _coerce_status(api_meta.get("status"))
            method = str(api_meta.get("method", ""))
            var = f"response{resp_n}"
            lines += _arm_wait(var, _url_prefix(endpoint), method)
            emit_action(step_type, route, target, label)
            lines.append(
                f"  // expected API failure: {_comment(endpoint)} "
                f"(HTTP {api_meta.get('status', '?')})"
            )
            lines.append(f"  const res{resp_n} = await {var};")
            lines.append(_status_assertion(f"res{resp_n}", status, endpoint))
            asserted = True
            resp_n += 1
            lines.append("")
            i += 2
            continue

        if step_type in ("navigation", "click", "input"):
            emit_action(step_type, route, target, label)

        elif step_type == "api_error":
            # Standalone API error (no immediately preceding interaction): bind a
            # short post-hoc wait so we still assert rather than just comment.
            endpoint = str(metadata.get("endpoint", ""))
            status = _coerce_status(metadata.get("status"))
            method = str(metadata.get("method", ""))
            method_clause = (
                f" && r.request().method() === '{_ts_str(method.upper())}'"
                if method
                else ""
            )
            lines.append(
                f"  // expected API failure: {_comment(endpoint)} "
                f"(HTTP {metadata.get('status', '?')})"
            )
            lines.append(
                f"  const res{resp_n} = await page.waitForResponse("
            )
            lines.append(
                f"    (r) => r.url().includes('{_ts_str(_url_prefix(endpoint))}'){method_clause},"
            )
            lines.append("  );")
            lines.append(_status_assertion(f"res{resp_n}", status, endpoint))
            asserted = True
            resp_n += 1

        elif step_type == "exception":
            name = str(metadata.get("name", "Error"))
            lines.append(
                f"  expect(pageErrors.some((m) => m.includes('{_ts_str(_comment(name))}')), "
                f"'the reported {_comment(name)} must not reproduce').toBe(false);"
            )
            asserted = True

        lines.append("")
        i += 1

    if not asserted:
        lines.append(
            "  // Navigation-only trace: no terminal failure was captured to assert on."
        )
        lines.append(
            "  // See the replayability warnings above; add a fixture/assertion to make this a"
        )
        lines.append("  // true regression test.")

    lines.append("});")
    return "\n".join(lines) + "\n"
