"""What ``stepstitch init`` writes into an application — pure templates, no I/O.

Everything lands under one ``stepstitch/`` directory in the target project plus a
manifest, so ``stepstitch init --uninstall`` can remove exactly what init created
and nothing else. No template ever contains a credential: the ingest proxy reads
``STEPSTITCH_INGEST_TOKEN`` from the server environment at runtime, which is the
same rule the documented hand-written proxies follow.

Stdlib-only, like the CLI that imports it.
"""
from __future__ import annotations

import json
from typing import Any, Dict, Mapping, Optional

__all__ = ["MANIFEST_NAME", "FRAMEWORKS", "detect_framework", "scaffold_files"]

MANIFEST_NAME = ".stepstitch-init.json"
FRAMEWORKS = ("next", "express", "browser")

# Default dev-server origins per framework, used for the synthetic repro config.
DEFAULT_APP_URLS = {
    "next": "http://localhost:3000",
    "express": "http://localhost:3000",
    "browser": "http://localhost:4173",
}


def detect_framework(package_json: Optional[Mapping[str, Any]]) -> str:
    """Classify the target project from its package.json (None = no package.json)."""
    if not package_json:
        return "browser"
    deps: Dict[str, Any] = {}
    for key in ("dependencies", "devDependencies"):
        section = package_json.get(key)
        if isinstance(section, Mapping):
            deps.update(section)
    if "next" in deps:
        return "next"
    if "express" in deps:
        return "express"
    return "browser"


def _tracker_setup(app_id: str, ingest_endpoint: str) -> str:
    return f"""// Generated by `stepstitch init`. Safe to edit — rerunning init never
// overwrites a file you have changed.
//
// Wires the StepStitch tracker the safe way: capture stays OFF until your
// consent manager calls grantConsent, nothing is sent anywhere except your own
// same-origin ingest proxy, and the report control is plain DOM you can style.
import {{ StepStitchTracker, mountReporter }} from "@stepstitch/tracker";

export const tracker = new StepStitchTracker({{
  appId: {json.dumps(app_id)},
  ingestEndpoint: {json.dumps(ingest_endpoint)},
  maxFootsteps: 40,
}});

// Call this from your consent manager when the user opts in.
export function enableStepStitch(consentVersion = "v1") {{
  tracker.grantConsent(consentVersion);
}}

// Call on a failed fetch/XHR so the trace records the structural failure
// (status + endpoint template), never the response body.
export function recordApiFailure(status, url, method = "GET") {{
  tracker.recordApiError(status, url, method);
}}

// Mount the "Report a problem" control wherever it belongs in your UI.
export function mountReportControl(container) {{
  return mountReporter({{ tracker, projectId: {json.dumps(app_id)}, container }});
}}
"""


def _next_proxy(host: str) -> str:
    return f"""// Generated by `stepstitch init`. Move this file to
// app/api/stepstitch/route.ts (App Router) so the tracker's ingestEndpoint
// "/api/stepstitch" resolves to it.
//
// The browser never talks to StepStitch directly and never sees the ingest
// token: this server route forwards the payload and attaches the credential
// from the server environment.
const HOST = process.env.STEPSTITCH_HOST ?? {json.dumps(host)};

export async function POST(request: Request) {{
  const body = await request.text();
  const upstream = await fetch(`${{HOST}}/api/stepstitch/v1/session`, {{
    method: "POST",
    headers: {{
      "Content-Type": "application/json",
      Authorization: `Bearer ${{process.env.STEPSTITCH_INGEST_TOKEN ?? ""}}`,
    }},
    body,
  }});
  return new Response(await upstream.text(), {{ status: upstream.status }});
}}
"""


def _express_proxy(host: str) -> str:
    return f"""// Generated by `stepstitch init`. Mount in your Express app:
//
//   import {{ stepstitchIngestProxy }} from "./stepstitch/ingest-proxy.mjs";
//   app.post("/ingest", express.text({{ type: "*/*" }}), stepstitchIngestProxy);
//
// The browser never talks to StepStitch directly and never sees the ingest
// token: this middleware forwards the payload and attaches the credential from
// the server environment.
const HOST = process.env.STEPSTITCH_HOST ?? {json.dumps(host)};

export async function stepstitchIngestProxy(req, res) {{
  const upstream = await fetch(`${{HOST}}/api/stepstitch/v1/session`, {{
    method: "POST",
    headers: {{
      "Content-Type": "application/json",
      Authorization: `Bearer ${{process.env.STEPSTITCH_INGEST_TOKEN ?? ""}}`,
    }},
    body: typeof req.body === "string" ? req.body : JSON.stringify(req.body),
  }});
  res.status(upstream.status).send(await upstream.text());
}}
"""


def _standalone_proxy(host: str) -> str:
    return f"""// Generated by `stepstitch init`. A standalone same-origin ingest proxy for
// apps without a Node server framework — run beside your static server:
//
//   STEPSTITCH_INGEST_TOKEN=... node stepstitch/ingest-proxy.mjs
//
// and point the tracker's ingestEndpoint at http://localhost:8322/ingest.
import {{ createServer }} from "node:http";

const HOST = process.env.STEPSTITCH_HOST ?? {json.dumps(host)};
const PORT = Number(process.env.STEPSTITCH_PROXY_PORT ?? 8322);

createServer((req, res) => {{
  if (req.method !== "POST") {{
    res.writeHead(405);
    return res.end();
  }}
  let body = "";
  req.on("data", (chunk) => (body += chunk));
  req.on("end", async () => {{
    const upstream = await fetch(`${{HOST}}/api/stepstitch/v1/session`, {{
      method: "POST",
      headers: {{
        "Content-Type": "application/json",
        Authorization: `Bearer ${{process.env.STEPSTITCH_INGEST_TOKEN ?? ""}}`,
      }},
      body,
    }});
    res.writeHead(upstream.status, {{ "content-type": "application/json" }});
    res.end(await upstream.text());
  }});
}}).listen(PORT, "127.0.0.1", () =>
  console.log(`stepstitch ingest proxy on http://127.0.0.1:${{PORT}}/ingest`)
);
"""


def _readme(framework: str, app_id: str, ingest_endpoint: str) -> str:
    mount = {
        "next": "Move `ingest-route.ts` to `app/api/stepstitch/route.ts`.",
        "express": "Mount `ingest-proxy.mjs` on a POST route (instructions at the "
                   "top of the file).",
        "browser": "Run `node stepstitch/ingest-proxy.mjs` beside your static "
                   "server (instructions at the top of the file).",
    }[framework]
    return f"""# StepStitch wiring for `{app_id}` (generated by `stepstitch init`)

Detected framework: **{framework}**. Three steps remain, in order:

1. **Install the tracker:** `npm install @stepstitch/tracker`
2. **Mount the ingest proxy.** {mount}
   Set `STEPSTITCH_INGEST_TOKEN` in the SERVER environment — `stepstitch start`
   printed it. It must never appear in browser code, and no generated file
   contains it.
3. **Wire the tracker** from `tracker-setup.js`: call `enableStepStitch()` from
   your consent manager, `recordApiFailure(...)` on failed requests, and
   `mountReportControl(el)` where the "Report a problem" control belongs.

The tracker records structural footsteps only (routes, selectors, status
codes); the ingest endpoint here is `{ingest_endpoint}`.

Then check the wiring end-to-end:

```
stepstitch doctor
```

Undo everything init wrote (your own files are never touched):

```
stepstitch init --uninstall
```
"""


def scaffold_files(*, framework: str, app_id: str, host: str) -> Dict[str, str]:
    """relative path -> content, for one framework. Raises on an unknown framework."""
    if framework not in FRAMEWORKS:
        raise ValueError(f"unknown framework {framework!r}; supported: {', '.join(FRAMEWORKS)}")
    ingest_endpoint = {
        "next": "/api/stepstitch",
        "express": "/ingest",
        "browser": "http://localhost:8322/ingest",
    }[framework]
    files = {
        "stepstitch/tracker-setup.js": _tracker_setup(app_id, ingest_endpoint),
        "stepstitch/README.md": _readme(framework, app_id, ingest_endpoint),
    }
    if framework == "next":
        files["stepstitch/ingest-route.ts"] = _next_proxy(host)
    elif framework == "express":
        files["stepstitch/ingest-proxy.mjs"] = _express_proxy(host)
    else:
        files["stepstitch/ingest-proxy.mjs"] = _standalone_proxy(host)
    return files
