import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { LiveDemo } from "@/components/live-demo";
import { SAMPLE_TRACE } from "@/lib/stepstitch";

// The panel may silently fall back to the bundled sample, so the section copy around it is
// source-neutral and THIS component carries the provenance disclosure. These tests pin that
// disclosure to the source field for both states — the honesty contract of the homepage demo.

vi.mock("@vercel/analytics", () => ({ track: () => {} }));

beforeAll(() => {
  class IO {
    observe() {}
    unobserve() {}
    disconnect() {}
    takeRecords() {
      return [];
    }
  }
  vi.stubGlobal("IntersectionObserver", IO);
  vi.stubGlobal("matchMedia", (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addEventListener: () => {},
    removeEventListener: () => {},
    addListener: () => {},
    removeListener: () => {},
    dispatchEvent: () => false,
  }));
});

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

function stubTrace(source: "live" | "sample") {
  vi.stubGlobal("fetch", async () => ({
    ok: true,
    json: async () => ({ ...SAMPLE_TRACE, source }),
  }));
}

describe("LiveDemo provenance disclosure", () => {
  it("labels a live trace as coming from a running service", async () => {
    stubTrace("live");
    render(<LiveDemo />);
    expect(await screen.findByText("live trace")).toBeTruthy();
    expect(
      screen.getByText(/Fetched just now from a running StepStitch service/i),
    ).toBeTruthy();
    // The live disclosure never appears alongside the sample badge, and vice versa.
    expect(screen.queryByText(/Bundled synthetic sample/i)).toBeNull();
  });

  it("calls the fallback a production-generated synthetic sample", async () => {
    stubTrace("sample");
    render(<LiveDemo />);
    expect(await screen.findByText("sample trace")).toBeTruthy();
    expect(
      screen.getByText(/Bundled synthetic sample, generated by the production pipeline/i),
    ).toBeTruthy();
    expect(screen.queryByText(/running StepStitch service/i)).toBeNull();
  });
});
