"""Regenerate server/fonts.py — the operator console's embedded typeface.

The console is a single self-contained page served under ``default-src 'none'``, so it cannot
fetch a font over the network. A system font stack is the clearest visual tell that something is
an internal tool rather than a product, so the typeface ships as a base64 ``data:`` URI instead
and the CSP grants exactly one extra directive (``font-src data:``) — which cannot reach the
network.

Only the SANS is embedded. Code blocks use the platform monospace stack: system mono (SF Mono,
Menlo, Consolas) is already good and is not what makes an interface look generic, so paying
another ~95KB for it is not worth it.

One VARIABLE file covers every weight from 100 to 900, which is why this is ~93KB rather than
four separate static cuts.

Geist is (c) 2023 Vercel in collaboration with basement.studio, under the SIL Open Font License
1.1 — which explicitly permits embedding.

Run after upgrading the `geist` package:

    python3 scripts/embed_console_font.py
"""
from __future__ import annotations

import base64
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SOURCE = REPO / "web/node_modules/geist/dist/fonts/geist-sans/Geist-Variable.woff2"
TARGET = REPO / "server/fonts.py"

TEMPLATE = '''"""Geist Variable, embedded as base64.

GENERATED by scripts/embed_console_font.py — do not hand-edit.

The operator console is a single self-contained page under ``default-src 'none'``; it cannot
fetch a font, so the typeface travels inside the page as a ``data:`` URI. One variable file
covers weights 100-900. Code uses the platform monospace stack rather than a second embedded
face.

Geist is (c) 2023 Vercel in collaboration with basement.studio, SIL Open Font License 1.1.
"""

GEIST_SANS_WOFF2_B64 = "{b64}"
'''


def main() -> int:
    if not SOURCE.exists():
        print(f"missing {SOURCE}\nrun `npm ci` in web/ first", file=sys.stderr)
        return 1
    raw = SOURCE.read_bytes()
    b64 = base64.b64encode(raw).decode("ascii")
    TARGET.write_text(TEMPLATE.format(b64=b64), encoding="utf-8")
    print(f"{SOURCE.name}: {len(raw):,}B -> {len(b64):,} base64 chars")
    print(f"wrote {TARGET.relative_to(REPO)} ({TARGET.stat().st_size:,}B)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
