#!/usr/bin/env python3
"""Recompute the pinned script_sha256 for every corpus entry, in place.

Run after a DELIBERATE compiler change, then commit the diff — the diff itself
is the review artifact showing which generated bytes moved:

    python scripts/refresh_repro_corpus.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "service"))

from stepstitch_service.repro_eval import evaluate_corpus  # noqa: E402

CORPUS = ROOT / "examples" / "repro" / "reproduction-corpus.json"


def main() -> int:
    doc = json.loads(CORPUS.read_text())
    result = evaluate_corpus(doc)
    by_name = {e.name: e for e in result.entries}
    changed = 0
    for entry in doc["entries"]:
        computed = by_name[entry["name"]].script_sha256
        if computed is None:
            continue
        if entry["expect"].get("script_sha256") != computed:
            entry["expect"]["script_sha256"] = computed
            changed += 1
    CORPUS.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"refreshed {changed} sha(s) -> {CORPUS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
